apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: gaming
data:
  config.yaml: |
    tunnel: <YOUR-CLOUDFLARE-TUNNEL-UUID>
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-chunked-encoding: true
    ingress:
      - hostname: <YOUR-PANEL-SUBDOMAIN> # e.g. mc-panel.yourdomain.com
        service: http://minecraft-server.gaming.svc.cluster.local:8080
      - hostname: <YOUR-SFTP-SUBDOMAIN> # e.g. mc-sftp.yourdomain.com
        service: tcp://minecraft-server.gaming.svc.cluster.local:2222
      - service: http_status:404
