apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: gaming
  labels:
    app: minecraft
spec:
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: voice
    port: 24454
    protocol: UDP
    targetPort: 24454
  - name: panel-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: sftp
    port: 2222
    protocol: TCP
    targetPort: 22
  selector:
    app: minecraft
  type: ClusterIP
